

<?php
// module/Album/view/album/album/add.phtml:

$title = 'Login';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('login', array('action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php if($error){ ?>
    <div class="alert alert-danger">
        <span class="glyphicon glyphicon-remove"></span><strong>Login failed.</strong>
    </div>
<?php } ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('name')); ?>
</div >

<div class="form-group">
    <?php echo $this->formRow($form->get('password')); ?>
</div >

<?php echo $this->formSubmit($form->get('login')); ?>


<?php echo $this->form()->closeTag(); ?>








